const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const WebSocket=require('ws');
const PORT=process.env.PORT||10000;const rooms=new Map();const GRACE=10*60*1000;
const server=http.createServer((req,res)=>{let p=(req.url||'/').split('?')[0];if(p==='/')p='/index.html';const root=path.resolve(__dirname,'public');const f=path.resolve(root,'.'+p);if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end('Forbidden')}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}const t={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(f)]||'application/octet-stream';res.writeHead(200,{'Content-Type':t,'Cache-Control':'no-store'});res.end(d)})});
const wss=new WebSocket.Server({server});const code=()=>{const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<5;i++)s+=c[crypto.randomInt(c.length)];return s};const id=()=>crypto.randomBytes(18).toString('hex');const send=(w,m)=>w&&w.readyState===WebSocket.OPEN&&w.send(JSON.stringify(m));
const pub=r=>r.players.map((p,i)=>({slot:i,name:p.name,score:p.score,connected:!!p.ws&&p.ws.readyState===WebSocket.OPEN}));const bc=(r,m)=>r.players.forEach(p=>send(p.ws,m));const state=r=>bc(r,{type:'state',players:pub(r),turn:r.turn,challenge:r.challenge,roomCode:r.code});const slot=(r,pid)=>r.players.findIndex(p=>p.id===pid);const cleanup=r=>{clearTimeout(r.timer);r.timer=setTimeout(()=>{if(r.players.every(p=>!p.ws||p.ws.readyState!==WebSocket.OPEN))rooms.delete(r.code)},GRACE)};
wss.on('connection',ws=>{ws.alive=true;ws.on('pong',()=>ws.alive=true);ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return send(ws,{type:'error',message:'Invalid message.'})};
if(m.type==='create'){let c=code();while(rooms.has(c))c=code();const p={id:id(),name:String(m.name||'Player 1').slice(0,30),score:0,ws};const r={code:c,players:[p],turn:0,challenge:null,timer:null};rooms.set(c,r);ws.room=c;ws.pid=p.id;return send(ws,{type:'room',code:c,slot:0,playerId:p.id,players:pub(r),turn:0})}
if(m.type==='join'){const c=String(m.code||'').replace(/\s/g,'').toUpperCase(),r=rooms.get(c);if(!r)return send(ws,{type:'error',message:'Room not found. Ask your partner for a fresh room code.'});let s=m.playerId?slot(r,m.playerId):-1;if(s<0){if(r.players.length>=2)return send(ws,{type:'error',message:'This room is full.'});const p={id:id(),name:String(m.name||'Player 2').slice(0,30),score:0,ws};r.players.push(p);s=r.players.length-1}else{r.players[s].ws=ws;if(m.name)r.players[s].name=String(m.name).slice(0,30)}clearTimeout(r.timer);ws.room=c;ws.pid=r.players[s].id;send(ws,{type:'joined',code:c,slot:s,playerId:ws.pid,players:pub(r),turn:r.turn,challenge:r.challenge});state(r);if(r.players.length===2&&r.players.every(p=>p.ws&&p.ws.readyState===WebSocket.OPEN))bc(r,{type:'ready'});return}
const r=rooms.get(ws.room);if(!r)return send(ws,{type:'error',message:'Room is no longer active. Create a new room.'});const s=slot(r,ws.pid);if(s<0)return send(ws,{type:'error',message:'Session expired. Rejoin the room.'});
if(m.type==='challenge'){if(r.players.length<2||!r.players.every(p=>p.ws&&p.ws.readyState===WebSocket.OPEN))return send(ws,{type:'error',message:'Wait until both players are connected.'});if(r.turn!==s)return send(ws,{type:'error',message:"It is your partner's turn."});r.challenge=Array.isArray(m.challenge)?m.challenge:null;bc(r,{type:'challenge',challenge:r.challenge,turn:r.turn});return}
if(m.type==='score'){if(r.turn!==s||r.players.length<2)return;const pts=Math.max(0,Math.min(10,Number(m.points)||0));r.players[s].score+=pts;r.challenge=null;r.turn=1-s;state(r);if(r.players[s].score>=50)bc(r,{type:'winner',player:s});return}
if(m.type==='claimTurn'){if(r.players.length===2&&r.players.every(p=>p.ws&&p.ws.readyState===WebSocket.OPEN)){r.turn=s;r.challenge=null;state(r)}}
});ws.on('close',()=>{const r=rooms.get(ws.room);if(!r)return;const s=slot(r,ws.pid);if(s>=0&&r.players[s].ws===ws)r.players[s].ws=null;bc(r,{type:'presence',players:pub(r)});cleanup(r)})});
setInterval(()=>wss.clients.forEach(ws=>{if(ws.alive===false)return ws.terminate();ws.alive=false;ws.ping()}),25000);server.listen(PORT,'0.0.0.0',()=>console.log('Us vs Us 2.1 listening on '+PORT));